### ISSUE TITLE
Designate 'campus email only' in directory block

### ISSUE THREAD

**Issue by kanarb** [ucsc/ucsc-gutenberg-blocks#93]
In incident INC1328282, Angie Steele has the following request:

This is a feature request for the Campus Directory Block in UCSC WordPress:

In the option for "Information to Display", it would be great if for "Email", we could designate selecting "Campus Email only" from the Campus Directory.

**Comment by superkumario64** [comment]
@teresasilva71 there was an email thread about this one. Are we ready to proceed with this feature?

**Comment by teresasilva71** [comment]
Yes, please proceed. It's a great idea...not sure why we didn't think of it earlier.
Would it be "UCSC Email Only" and "All Email Addresses"? 
Something like that?
(We should remove "Campus" because we're not all on campus anymore. We're moving to describing things with "UCSC" instead of Campus.)
Thank you!

**Comment by superkumario64** [comment]
@kanarb @teresasilva71 This issue is now resolved on production.
